var documenterSearchIndex = {"docs": [

{
    "location": "#",
    "page": "Traceur.jl",
    "title": "Traceur.jl",
    "category": "page",
    "text": ""
},

{
    "location": "#Traceur.jl-1",
    "page": "Traceur.jl",
    "title": "Traceur.jl",
    "category": "section",
    "text": "Performance linting for Julia."
},

{
    "location": "#Traceur.@trace",
    "page": "Traceur.jl",
    "title": "Traceur.@trace",
    "category": "macro",
    "text": "@trace(functioncall(args...), maxdepth=2, modules=[])\n\nAnalyse functioncall(args...) for common performance problems and print them to the terminal.\n\nOptional arguments:\n\nmaxdepth constrols how far Traceur recurses through the call stack.\nIf modules is nonempty, only warnings for methods defined in one of the modules specified will be printed.\n\n\n\n\n\n"
},

{
    "location": "#Traceur.warnings",
    "page": "Traceur.jl",
    "title": "Traceur.warnings",
    "category": "function",
    "text": "warnings(f; kwargs...)::Vector{Traceur.Warnings}\n\nCollect all warnings generated by Traceur\'s analysis of the execution of the no-arg function f and return them.\n\nPossible keyword arguments:\n\nmaxdepth=typemax(Int) constrols how far Traceur recurses through the call stack.\nIf modules is nonempty, only warnings for methods defined in one of the modules specified will be printed.\n\n\n\n\n\n"
},

{
    "location": "#Normal-Use-1",
    "page": "Traceur.jl",
    "title": "Normal Use",
    "category": "section",
    "text": "Traceur.@traceTraceur.warnings"
},

{
    "location": "#Traceur.@check",
    "page": "Traceur.jl",
    "title": "Traceur.@check",
    "category": "macro",
    "text": "@check fun(args...) nowarn=[] maxdepth=typemax(Int)\n\nRun Traceur on fun, and throw an error if any warnings occur inside functions tagged with @should_not_warn or specified in nowarn.\n\n\n\n\n\n"
},

{
    "location": "#Traceur.check",
    "page": "Traceur.jl",
    "title": "Traceur.check",
    "category": "function",
    "text": "check(f::Function)\n\nRun Traceur on f, and throw an error if any warnings occur inside functions tagged with @should_not_warn.\n\n\n\n\n\n"
},

{
    "location": "#Traceur.@should_not_warn",
    "page": "Traceur.jl",
    "title": "Traceur.@should_not_warn",
    "category": "macro",
    "text": "@shouldnotwarn function foo(x)     ...   end\n\nAdd foo to the list of functions in which no warnings may occur (checkd by @check).\n\n\n\n\n\n"
},

{
    "location": "#Tests-1",
    "page": "Traceur.jl",
    "title": "Tests",
    "category": "section",
    "text": "Traceur.@checkTraceur.checkTraceur.@should_not_warn"
},

]}
